// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721Enumerable$Type } from "./ERC721Enumerable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Enumerable"]: ERC721Enumerable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol:ERC721Enumerable"]: ERC721Enumerable$Type;
  }
}
