// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Pausable$Type } from "./Pausable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Pausable"]: Pausable$Type;
    ["@openzeppelin/contracts/utils/Pausable.sol:Pausable"]: Pausable$Type;
  }
}
