// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC721$Type } from "./IERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC721"]: IERC721$Type;
    ["@openzeppelin/contracts/token/ERC721/IERC721.sol:IERC721"]: IERC721$Type;
  }
}
