// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HardhatFoundryERC721$Type } from "./HardhatFoundryERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HardhatFoundryERC721"]: HardhatFoundryERC721$Type;
    ["contracts/HardhatFoundryERC721.sol:HardhatFoundryERC721"]: HardhatFoundryERC721$Type;
  }
}
