// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721URIStorage$Type } from "./ERC721URIStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721URIStorage"]: ERC721URIStorage$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol:ERC721URIStorage"]: ERC721URIStorage$Type;
  }
}
