// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IAccessControl$Type } from "./IAccessControl";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAccessControl"]: IAccessControl$Type;
    ["@openzeppelin/contracts/access/IAccessControl.sol:IAccessControl"]: IAccessControl$Type;
  }
}
