// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721Pausable$Type } from "./ERC721Pausable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Pausable"]: ERC721Pausable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol:ERC721Pausable"]: ERC721Pausable$Type;
  }
}
