// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC4906$Type } from "./IERC4906";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC4906"]: IERC4906$Type;
    ["@openzeppelin/contracts/interfaces/IERC4906.sol:IERC4906"]: IERC4906$Type;
  }
}
