// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721Burnable$Type } from "./ERC721Burnable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Burnable"]: ERC721Burnable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol:ERC721Burnable"]: ERC721Burnable$Type;
  }
}
