// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AccessControl$Type } from "./AccessControl";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AccessControl"]: AccessControl$Type;
    ["@openzeppelin/contracts/access/AccessControl.sol:AccessControl"]: AccessControl$Type;
  }
}
