// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC721Enumerable$Type } from "./IERC721Enumerable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC721Enumerable"]: IERC721Enumerable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol:IERC721Enumerable"]: IERC721Enumerable$Type;
  }
}
